tacc.c: fix build failure when time_t is 64 bits
Build can fail if time_t is 64 bits and not 32 bits because of the
following warning (which results in a build failure due to -Werror):

tacc.c: In function 'main':
tacc.c:346:25: error: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'time_t' {aka 'long long int'} [-Werror=format=]
         sprintf(buf, "%lu", time(0));
                       ~~^   ~~~~~~~
                       %llu

So replace %lu by %llu

Fixes:
 - http://autobuild.buildroot.org/results/874433d8cb30d21332f23024081a8b6d7b3254ae

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>